project:
  type: website
  render:
    - index.qmd
    - archives.qmd

website:
  title: "`utilitR`"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://book.utilitr.org
        text: Documentation
      - href: archives.qmd
        text: Archives
      - href: https://datalab.sspcloud.fr
        text: "SSPCloud"
      - icon: github
        href: https://github.com/InseeFrLab/utilitr
    background: "#4758AB"
  twitter-card:
    image: /images/utilitr-logo.png

format:
  html:
    theme: [cosmo, style.scss]
    css: styles.css
    toc: true

